AWSTemplateFormatVersion: 2010-09-09
Description: IaC pipeline example resources

Parameters:
  AppName:
    Type: String
    Description: "Name of App"
    Default: "myapp"

  AppEnv:
    Type: String
    Description: "App Environment [ dev | test | prod ]"
    AllowedValues:
      - dev
      - test
      - prod    
    Default: "dev"

Resources:
  myBucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Sub '${AppName}-${AWS::AccountId}-${AppEnv}-cf'
      Tags:
        - Key: Environment
          Value: !Ref AppEnv
        - Key: Application
          Value: !Ref AppName
        - Key: Region
          Value: !Ref AWS::Region
        - Key: ManagedBy
          Value: "CloudFormation"

  dlQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${AppName}-${AppEnv}-queue-cf-dl'
      Tags:
        - Key: Environment
          Value: !Ref AppEnv
        - Key: Application
          Value: !Ref AppName
        - Key: Region
          Value: !Ref AWS::Region
        - Key: ManagedBy
          Value: "CloudFormation"

  mainQueue: 
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: !Sub '${AppName}-${AppEnv}-queue-cf-main'
      RedrivePolicy: 
        deadLetterTargetArn: !GetAtt dlQueue.Arn
        maxReceiveCount: 4
      Tags:
        - Key: Environment
          Value: !Ref AppEnv
        - Key: Application
          Value: !Ref AppName
        - Key: Region
          Value: !Ref AWS::Region
        - Key: ManagedBy
          Value: "CloudFormation"
